// -----------------------------------------------------------------------------
// CuteJet by CyaNn & ALGEA
// NE PAS MODIFIER CETTE PARTIE DU CODE

// variables
set font = game.createFont("emulogic", 12, game.color.WHITE);


// stage
set stage = game.createStage(0, -10);
set gameLayer = stage.createLayer();
set scoreLayer = stage.createLayer();

include("CuteJet.include1");

// On commence à partir d'ici **
// A NOUS DE JOUER
// -----------------------------------------------------------------------------

set hero = gameLayer.createActor("PlanetCute/Character Pink Girl", 250, 250);
hero.hitCircle().typeDynamic()

set a = 0;

loop (10) {
	
	gameLayer.createActor("PlanetCute/Dirt Block", a, 0);

	a += 100;
}

hero.applyForceX(10)







// -----------------------------------------------------------------------------
// NE PAS MODIFIER LA PARTIE SUIVANTE DU CODE

include("CuteJet.include2");
